### ISSUE TITLE
Getting an incorrect parse error when the label in a child parameter of a list uses the & symbol

### ISSUE THREAD

**Issue by theperrygroup** [Adobe-Muse/brackets-mucow-language-support#7]
This will cause a `xmlParseEntityRef:no name` error

```
<list name="demo" defaultValue="child" label="List Demo>
    <value name="child" label="This & That"/>
</list>
```

**Comment by JeffryBooher** [comment]
Yeah it wants you to encode it.  

This should work for you:

`<value name="child" label="This &amp; That" />`

Let us know if you still see problems.

**Comment by theperrygroup** [comment]
No, I figured that but the widget will still open up in Muse without any problems. I was saying that this error might not be necessary unless I'm missing something.

**Comment by JeffryBooher** [comment]
Yeah the Muse XML parser is a pretty forgiving whereas the validator isn't.  Muse may also move to a more stricter XML parser in the future so it's better to validate your widget to the standard grammar regardless of what Muse will accept.
